targets:
  # Existing targets
  - https://career.paradoxplaza.com/jobs
  - https://careers.avalanchestudios.com/jobs
  - https://career.embark-studios.com/jobs
  - https://jobs.fatsharkgames.com/jobs
  - https://jobs.machinegames.com/jobs
  - https://jobs.stunlock.com/jobs
  - https://jobs.frictionalgames.com/jobs
  - https://jobs.coffeestain.se/jobs
  - https://jobs.tarsier.se/jobs
  - https://jobs.starbreeze.com/jobs
  - https://jobs.arrowheadgamestudios.com/jobs
  - https://career.snowprintstudios.com/jobs
  - https://jobs.neongiant.se/jobs
  - https://jobs.mightanddelight.com/jobs
  - https://career.goodbyekansas.com/jobs
  - https://career.edisen.com/jobs
  - https://www.ilpvfx.com/jobs/
  - https://filmgate.se/jobs/
  - https://fablefx.com/jobs/
  - https://jobs.ea.com/en_US/careers/SearchJobs/?8171=%5B10612%5D&8171_format=5683&listFilterMode=1&jobRecordsPerPage=20&

  # French GAME studios
  - https://www.ubisoft.com/en-us/company/careers/search
  - https://dont-nod.com/en/careers/
  - https://www.gameloft.com/jobs
  - https://www.quanticdream.com/en/careers/
  - https://www.asobostudio.com/careers/
  - https://www.voodoo.com/careers/
  - https://www.homagames.com/careers/
  - https://oldskullgames.com/careers/

  # French VFX / Animation studios
  - https://buf.com/jobs/
  - https://careers.smartrecruiters.com/RodeoFX
  - https://careers.smartrecruiters.com/RodeoFX/mikros-animation---career-page-%28english%29
  - https://www.mpcvfx.com/en/careers/
  - https://apply.workable.com/one-of-us/
  - https://www.themill.com/careers/
  - https://unit-image.fr/jobs/
  - https://brunchstudio.tv/jobs/
  - https://mathematic.tv/jobs/
  - https://www.nki.tv/jobs/

custom:
  # Add custom parsers later for these
  # - https://www.ea.com/careers
  # - https://careers.king.com/

roles:
  include:
    - Engineer
    - Developer
    - Programmer
    - Technical Artist
    - Producer
    - Production
    - Coordinator
  soft_exclude:
    - Manager
    - Director
    - Lead
    - Intern

